### ISSUE TITLE
Move pre/post script execution to the container.

### ISSUE THREAD

**Issue by bouskaJ** [citrusframework/yaks#124]
We are still struggling with native pre/post script execution on the client station. Users are forced to have installed all tools/commands used by the script. Scripts have to be platform-independent that can be a big pain.

Discussed with @christophd , @nicolaferraro, and @VratislavHais we decided that we will move script execution to the YAKS container in order to unify the environment.

**Comment by bouskaJ** [comment]
Hi @christophd what's the progress of this issue? Yaks is losing a lot of value because of this (we are not able to run YAKS tests on windows machines because of this).

**Comment by llowinge** [comment]
Hello @christophd we had further discussion with @bouskaJ and we found out that for testing on Windows this feature request would probably not help, because all commands (including `kamel install`) would run in the linux container, so we wouldn't test kamel binary on Windows at all. 

We came up with these ideas:
* Having possibility to mark pre/post script to run in container (for eg. `sed abcd`) or off container (for eg. `kamel install`)
* Revisit existing tests and trying to remove dependency on linux specific commands (eg. avoid using `sed`, etc) - which will be probably hard, as sometimes it is really needed to be able to use bash functionalities (eg. loop, wait, etc)

Do you have any suggestions how to test Camel K with yaks on Windows ?

**Comment by christophd** [comment]
@llowinge @bouskaJ yes, these are the points that make this task so hard to implement. I have had the same issues in mind when thinking about solutions for this.

So if we mark some scripts to be run on the host and others to be run on the container there is now way to have a predefined ordering and mixing of scripts. Like all scripts on the host will be run first and then all scripts to be run on the container will follow. Would that be an issue?

Also I think running any script provided by the user inside the container (= inside the container infrastructure) will raise severe security concerns.

Would something like https://www.cygwin.com/ help us here?

**Comment by bouskaJ** [comment]
Hi, @christophd we already have `cygwin` installed on our machines. We already experimented with the Windows Linux subsystem (https://docs.microsoft.com/en-us/windows/wsl/install-win10). None of those solutions worked as expected (more info from @VratislavHais ).

Can we create a new pod for script execution to avoid the security issue?

Thinking about script separation (container/host) I am not 100% sure that this is the best solution. What about empowering YAKS steps to be able to prepare ENV for the test execution (create secrets, install operators from OperatorHub etc.) WDYT @christophd , @llowinge

**Comment by christophd** [comment]
@bouskaJ +1 for moving this into YAKS steps. There is already a `yaks-kubernetes` module that is able to create custom resources and secrets from yaml files. We can extend this for creating any Kubernetes resource from yaml file.

In addition to that we can add support for variable placeholders in pre/post scripts and test resources so that you do not have to `sed` the YAKS_NAMESPACE in files

**Comment by christophd** [comment]
Closing as this should be solved with moving all into the YAKS steps
