### ISSUE TITLE
`verify Kafka message body` step does not actually verify

### ISSUE THREAD

**Issue by asmigala** [citrusframework/yaks#216]
During the refactoring in #141, the `verify Kafka message body` step was merged with a different step and now performs no verification of the received message, only sets the expected body. A separate step `receive Kafka message` must be used to perform the verification.

I'm not sure whether this is intentional or not, but it is very unexpected behaviour.

**Comment by christophd** [comment]
@asmigala oh yes that is intentional. it was not meant to cause confusion so. sorry for that. it aligns with other modules that also use the concept of first specifying the message (body, header, jsonpath validations and so on) and then actually do the receive and its validation in a separate step. 

this needs a clear documentation for sure.

**Comment by christophd** [comment]
the documentation has been updated/created 

Please have a look here: https://citrusframework.org/yaks/reference/0.2.0/html/index.html#kafka-receive
